### ISSUE TITLE
TransmitclientEvent only with 16 bit uint.

### ISSUE THREAD

**Issue by Cupiii** [c-true/FsConnect#15]
Hello Timian,

Thanks for the Library, which is really easy to use. 

I use this code to set the Com Stby Frequency in MSFS:

`
  fsConnect.MapClientEventToSimEvent(TestEnums.GroupId, TestEnums.EventId, FsEventNameId.ComStbyRadioSet);
  fsConnect.SetNotificationGroupPriority(TestEnums.GroupId);

  fsConnect.TransmitClientEvent(TestEnums.EventId, (uint)bcdStbyFreq, TestEnums.GroupId);
`
The problem is, that an uint BCD only has 4 digits. I'm Able to set com Frequency to 124.000 and 124.010 (using uint16 BCD 2400 and 2401 (the leading "1" in 100.000 is ommited)), but not to 124.005, which i am able in Garmin GNS 530.

 So i would need a TransmitClientEvent with an uint64, i guess.

Greetings 

Andreas

**Comment by TimianHeber** [comment]
Hi Andreas,

Sure, I'll get on it. Do you know if there are other requirements for the signature of TransmitClientEvent?
Anyway, I'll add the uint64 and hopefully push a new release this weekend, monday at the latest.

**Comment by Cupiii** [comment]
Thanks for your quick reply. Just got my Arduino to work with the ComStandbyFrequency.  ;-)

> Do you know if there are other requirements for the signature of TransmitClientEvent? (i.e. other data types)

Oh, no, i actually dont know,

**Comment by TimianHeber** [comment]
I found some information about an undocumented way on how to set 3 decimal frequencies (See link below). It seems to work, but I need a couple of days to clean things up, and need to investigate how to read these values back.

https://www.fsdeveloper.com/forum/threads/radio-com-frequencies-a-heads-up-about-potential-issues.451550/

**Comment by Cupiii** [comment]
Interesting, will try today.

**Comment by TimianHeber** [comment]
Hi Andreas, I have now finally pushed a new verision where I added a RadioManager. It should support 3 decimals for radio frequency so try it out or steal the code and see if it works for you. I'll add support for NAV radios shortly,
