### ISSUE TITLE
May not have permission to write SimConnect.cfg

### ISSUE THREAD

**Issue by TimianHeber** [c-true/FsConnect#4]
The SimConnect.cfg file is currently written to Executing assembly's location. This may be in an area where the process does not have access to write to.

Consider writing to the user's documents folder as the SimConnect.dll also looks here.

**Comment by josh2112** [comment]
Agreed... even if the file already exists, FsConnect insists on trying to overwrite it. Maybe just have a SimConnect constructor without hostname and port which will use the existing SimConnect.cfg?

**Comment by TimianHeber** [comment]
Good idea, thanks! 

I'll fix this and push a new version within the end of the week with support for either specifying location of SimConnect.cfg or parameterless constructor for using existing.
