### ISSUE TITLE
SimConnect.cfg in My Documents - conflict with other mods

### ISSUE THREAD

**Issue by thealx-eech** [c-true/FsConnect#6]
CJ4 mod team contacted me about conflict with my Kinetic Assistant, which uses your fsConnect.DLL, that SimConnect.cfg in My Documents cause their WASM module functionality problems. I have fixed it on my end, but you should consider to set local CFG placement as default:

public SimConnectFileLocation SimConnectFileLocation { get; set; } = SimConnectFileLocation.Local;

**Comment by dga711** [comment]
Got confirmation the SimConnect client that drives the WASM modules in MSFS looks for simconnect.cfg in documents etc.  first. For some reason.
Asobo will fix this in the future.
But it would still be good to apply the changes @thealx-eech suggested. Thank you

**Comment by TimianHeber** [comment]
Thanks for the feedback. I will change the default location as you suggested and push an update.
Any other suggestions and feature requests are always welcome!
